# Generated by Django 4.0.6 on 2022-07-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='onlink',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
    ]
